### ISSUE TITLE
Add sound to video player when code is on screen

### ISSUE THREAD

**Issue by 20095325** [NM-TAFE/dip-programming-prj-advanced-gui-awesome#21]
add play_sound function to update_video_data when code is on screen.

* Extra: Add a sound when code in no longer on the screen.

**Comment by MasterAirscrachDev** [comment]
easily generate sounds: https://sfxr.me/

**Comment by LukeyTheFireCube** [comment]
Would adding the package "playsound" to the requirements be alright?

**Comment by MasterAirscrachDev** [comment]
How do you add a package to front end js?

**Comment by MasterAirscrachDev** [comment]
Uhh no, stick with browser js, nodejs is for desktop applications

**Comment by 20095325** [comment]
@sdthinlay are we making progress on this?
