### ISSUE TITLE
Refactoring of remotellama

### ISSUE THREAD

**Issue by rafrafavi** [NM-TAFE/dip-programming-prj-advanced-gui-awesome#28]
Document this reference:
https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-awesome/blob/c831690b031c475c54b4fa094115f342456a0d34/app/remotellama.py#L6

Rename to remote_llama.py

Rename LlamaInterace class (should be good as just Llama)

Lastly, there is a very strange bastardization of Python's OOP mechanisms where standard methods are being used as pseudo-static methods, making the callers responsible for understanding this nuance. 

This needs to be fixed by either adding self and requiring the callers to change as well, or, what might be easier, is to add `staticmethod` decorators to the methods since this is how they are used. From what I can tell, the latter method would not have impact on callers.

**Comment by rafrafavi** [comment]
When you submit the PR please get @bhandareasmita to review

**Comment by Claire863** [comment]
Thanks Raf,

I am starting to work on it.
Wont forget to include @bhandareasmita for the review.

**Comment by rafrafavi** [comment]
Don't forget to open a draft PR early and link to this issue
