### ISSUE TITLE
Protect the main branch from direct commits

### ISSUE THREAD

**Issue by 20095325** [NM-TAFE/dip-programming-prj-advanced-gui-awesome#32]
@rafrafavi Could we protect the main branch from direct commits and make it so that at least one approval is required on a PR before merging?

None of us have any sort of admin permissions on the repo so we cannot change these settings.

**Comment by rafrafavi** [comment]
Done - usually I give admin to the team lead - if you can tell me who that is, we can make them admin on this repo
