### ISSUE TITLE
Open in IDE adds <br> tags to new lines

### ISSUE THREAD

**Issue by 20095325** [NM-TAFE/dip-programming-prj-advanced-gui-awesome#40]
We need the open in IDE function to remove or replace the <br> tags with "/n" new line characters.

**Comment by 20095325** [comment]
<img width="935" alt="image" src="https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-awesome/assets/125956528/9b1b98e6-262a-4e10-9713-bd06ff0d3db0">

**Comment by LukeyTheFireCube** [comment]
fixed the issue here: https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-awesome/pull/41
