### ISSUE TITLE
Missing docstrings in some functions

### ISSUE THREAD

**Issue by LukeyTheFireCube** [NM-TAFE/dip-programming-prj-advanced-gui-awesome#45]
Noticed that some functions are missing docstrings.
These functions include ones in different python files such as remotellama.py, pre_process.py and app.py.

**Comment by Claire863** [comment]
Just letting you know I am already modifying docstrings in remotellama.py
It is linked to issue #28, pull request #29 (pending review).

**Comment by LukeyTheFireCube** [comment]
alright, leaving you to that then
