### ISSUE TITLE
Open in IDE does not work

### ISSUE THREAD

**Issue by James-Makela** [NM-TAFE/dip-programming-prj-advanced-gui-awesome#5]
When clicking "Open in IDE", the IDE specified in the user settings opens, but does not open the chosen code snippet.

### Steps to reproduce:

1. Start the program with `python app.py` from the app directory
2. Open a video file
3. Capture a code snippet from a frame with code
4. Click "Open in IDE" above the new code snippet

- Result IDE opens, but does not open the code snippet

Tested with:
- vs code
- PyCharm

**Comment by rafrafavi** [comment]
Excellent description of the issue. Can you try and triage the issue and see which parts of the code are affected - you can also create a PR and associate with this issue? (Even this level of engagement should count towards your overall engagement with the project)

**Comment by James-Makela** [comment]
Thanks Raf, triaging lead me to the `utils.py` file, particularly the `send_code_snippet_to_ide()` function. PR is created and fixes the issue. 
I was not sure how, or if tests could be written to see if an external program is viewing the file.

**Comment by rafrafavi** [comment]
The best way to test things like that is to mock the call to the external program and only verify that it is being called with the correct parameters. Here's a simplified example:

```python
import unittest
from unittest.mock import patch
import subprocess


def write_to_file(snippet):
    print("I never get called!")
    return r"c:\a\b\c"


def send_code_snippet_to_ide(snippet):
    file_path = write_to_file(snippet)
    subprocess.run(["code", file_path])


class TestSendCodeSnippetToIDE(unittest.TestCase):
    @patch("__main__.write_to_file")
    @patch("subprocess.run")
    def test_send_code_snippet_to_ide(self, mock_run, mock_write):
        snippet = "print('Hello, World')"
        mock_write.return_value = r"C:\mock\path\filename.py"
        send_code_snippet_to_ide(snippet)
        mock_write.assert_called_once_with(snippet)
        mock_run.assert_called_once_with(["code", r"C:\mock\path\filename.py"])```

**Comment by rafrafavi** [comment]
Though TBF, this wouldn't have spotted the bug you got - I guess that is what functional testing is for :)
