### ISSUE TITLE
remotellama refactoring raise_for_status

### ISSUE THREAD

**Issue by Claire863** [NM-TAFE/dip-programming-prj-advanced-gui-awesome#52]
@20095325 

I see that you approved PR #29 (remotellama refactoring).

About the raise_for_status modification : 
Here if it fails, it will give a Traceback.
Instead should we use a try / except to handle the error?

I don't know how to 'generate' an error and don't know how to test and write a code to handle it.

Would appreciate your thought on this.

**Comment by 20095325** [comment]
@Claire863 you could try changing the url to something that is incorrect and then try testing that way.
