### ISSUE TITLE
Delete video from Video Save Path

### ISSUE THREAD

**Issue by josutcliffe** [NM-TAFE/dip-programming-prj-advanced-gui-awesome#56]
Using the _Delete_ button on a video listed on the Homepage removes the video from the user's view but does not delete the actual video from the user's _Video Save Path_.  

Researching online, this cannot be performed with JavaScript, and requires a server side solution/script, as noted here: https://stackoverflow.com/questions/19721621/how-to-delete-file-from-folder-using-javascript

**Comment by MasterAirscrachDev** [comment]
this is an issue but its to do with the backend and as such javascript isnt applicable here.
